#!/bin/bash

if [ "$#" != "1" ]; then
	echo "Usage: $0 file.rs"
	exit 1

fi

OPTS="-O"

if [ exscape.rs -nt libexscape-*.rlib ];
then
	echo -n 'Rebuilding exscape.rs ... '
	rustc $OPTS --crate-type=lib exscape.rs -L . || (echo 'Error compiling exscape.rs!'; exit 1)
	[ $? != 0 ] && exit $?
	echo 'done!'
fi

echo -n "Building $1 ... "
rustc $OPTS $1 -L . || (echo "Error compiling $1"; exit 1)
STATUS=$?
if [[ $STATUS == 0 ]]; then echo 'done!'; fi
exit $STATUS
